routes/web.php
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'SiteController@index')->name('home');

Route::get('/eventos', 'EventsController@list')->name('events');
Route::get('/evento/{slug}', 'EventsController@event')->name('event');
Route::get('/casas', 'PlacesController@list')->name('place.list');
Route::get('/casa/{slug}', 'PlacesController@place')->name('place');
// Route::get('/evento', function() { return view('events.event'); })->name('event');
Route::get('/categorias', 'SiteController@categories')->name('categories');
Route::post('/contato', 'SiteController@contact')->name('contact.send');
Route::get('/para-empresas', 'SiteController@forCompanies')->name('for.companies');
Route::get('/empresas/ativar/{token}', 'SiteController@activeCompanies')->name('active.companies');


Route::get('/contato', function() { return view('pages.contact'); })->name('contact');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function() {
    Route::get('/create-profile', function() {
        dd(Auth::user()->id);
    })->name('places.create');

    Route::get('/events', 'Admin\EventsController@list')->name('admin.events.list');
    Route::get('/events/{id}/promoters', 'Admin\EventsController@eventLists')->name('admin.event.promoters');
    Route::get('/events/{id}/export-sales-excel', 'Admin\EventsController@export')->name('admin.event.export.sales');
    Route::get('/events/{id}/listas', 'Admin\EventsController@eventLists')->name('admin.event.lists.vincular');
    Route::post('/events/attach-lists', 'Admin\EventsController@attachLists')->name('admin.event.attach.lists');
    Route::get('/events/{id}/edit', 'Admin\EventsController@edit')->name('admin.events.edit');
    Route::get('/events/create', 'Admin\EventsController@create')->name('admin.events.create');
    Route::post('/events/store', 'Admin\EventsController@store')->name('admin.events.store');
    Route::get('/events/{id}/minha-lista', 'Admin\EventsController@minhaLista')->name('admin.event.minha.lista');
    Route::post('/events/{id}/update', 'Admin\EventsController@update')->name('admin.events.update');
    Route::post('/events/{id}/upload-cover', 'Admin\EventsController@uploadCoverImage')->name('admin.events.upload-cover');
    Route::post('/events/attach-person', 'Admin\EventsController@attachPersonEventList')->name('admin.events.attach-person');
    Route::get('/events/{id}/portaria', 'Admin\EventsController@portaria')->name('admin.events.portaria');
    Route::get('/events/{id}/cadastro-caixa', 'Admin\EventsController@createCaixa')->name('admin.events.createCaixa');
    Route::post('/events/{id}/vincular-caixa', 'Admin\EventsController@vincularCaixa')->name('admin.events.vincularCaixa');
    Route::get('/events/{id}/desvincular-caixa/{user_id}', 'Admin\EventsController@desvincularCaixa')->name('admin.events.desvincularCaixa');
    Route::get('/events/{id}/lists', 'Admin\ListsController@index')->name('admin.events.lists');
    Route::get('/events/{id}/statistic', 'Admin\EventsController@statistic')->name('admin.events.statistic');
    Route::get('/events/{id}/create-bar', 'Admin\EventsController@createBar')->name('admin.events.createBar');
    Route::get('/events/{id}/produtos/{produto_id}/editar', 'Admin\EventsController@barEdit')->name('admin.event.produto.edit');
    Route::get('/events/{id}/produtos/{produto_id}', 'Admin\EventsController@barDesvinculate')->name('admin.event.produto.delete');
    Route::delete('/events/{id}/produtos/{produto_id}', 'Admin\EventsController@barDesvinculate')->name('admin.event.produto.delete');

    Route::get('/place/edit', 'Admin\PlacesController@edit')->name('admin.place.edit');
    Route::post('/place/update', 'Admin\PlacesController@update')->name('admin.place.update');
    Route::post('/place/upload-photo', 'Admin\PlacesController@uploadPhoto')->name('admin.place.upload-photo');
    Route::get('/galeries', 'Admin\GaleriesController@list')->name('admin.galeries');
    Route::get('/galery/{galery_id}', 'Admin\GaleriesController@galery')->name('admin.galery');
    Route::post('/galery/store', 'Admin\GaleriesController@store')->name('admin.galery.store');
    Route::post('/galery/{galery_id}/add-photos', 'Admin\GaleriesController@addPhotos')->name('admin.galery.addPhotos');

    Route::get('/promoters', 'Admin\PromotersController@index')->name('admin.promoters');
    Route::get('/promoters/cadastro', 'Admin\PromotersController@create')->name('admin.promoters.create');
    Route::get('/promoters/{id}/edit', 'Admin\PromotersController@edit')->name('admin.promoters.edit');
    Route::post('/promoters/{id}/update', 'Admin\PromotersController@update')->name('admin.promoters.update');
    Route::post('/promoters/store', 'Admin\PromotersController@store')->name('admin.promoters.store');
    Route::get('/events/{id}/promoters', 'Admin\PromotersController@eventsPromoters')->name('admin.event.promoters');
    Route::get('/events/{event_id}/promoters/desvincular/{id}', 'Admin\PromotersController@desvincularPromoter')->name('admin.event.desvincularPromoter');
    Route::post('/events/{id}/promoters/vinculate', 'Admin\PromotersController@eventsPromotersVinculate')->name('admin.event.promoters.vinculate');
    Route::post('/events/{id}/bar/vinculate', 'Admin\EventsController@eventsBarVinculate')->name('admin.event.bar.vinculate');
    Route::post('/events/bar/vinculate/update', 'Admin\EventsController@eventsBarUpdateVinculate')->name('admin.event.bar.update.vinculate');


    Route::get('/lists', 'Admin\ListsController@index')->name('admin.lists');
    Route::get('/list/{id}/edit', 'Admin\ListsController@edit')->name('admin.lists.edit.item');
    Route::post('/list/{id}/update', 'Admin\ListsController@update')->name('admin.lists.update.item');
    Route::post('/events/lists/store', 'Admin\ListsController@store')->name('admin.lists.store');
    Route::get('/events/lists/list-promoter', 'Admin\ListsController@getListPromoter')->name('admin.lists.listpromoter');


    /**
     * Usuarios
     */
    Route::get('/usuarios', 'Usuarios\UsuariosController@index')->name('usuarios.index');
    Route::get('/usuarios/cadastro', 'Usuarios\UsuariosController@create')->name('usuarios.create');
    Route::post('/usuario/store', 'Usuarios\UsuariosController@store')->name('usuario.store');
    Route::get('/usuario/{id}/delete', 'Usuarios\UsuariosController@destroy')->name('usuario.destroy');
    Route::get('/usuario/{id}/editar', 'Usuarios\UsuariosController@edit')->name('usuario.edit');
    Route::post('/usuario/{id}/update', 'Usuarios\UsuariosController@update')->name('usuario.update');

    /**
     * grupos produtos
     */
    Route::get('/grupos', 'Produtos\GruposProdutosController@index')->name('grupos.index');
    Route::post('/grupos/store', 'Produtos\GruposProdutosController@store')->name('admin.grupos.store');
    Route::get('/grupos/{id}/edit', 'Produtos\GruposProdutosController@edit')->name('admin.grupos.edit');
    Route::post('/grupos/update', 'Produtos\GruposProdutosController@update')->name('admin.grupos.update');

    /**
     * formas de pagamento
     */
    Route::get('/formas-pagamentos', 'FormaPagamento\FormasPagamentosController@index')->name('admin.formasPagamento');


    /**
     * PDV
     */
    Route::get('/forca-de-vendas', 'PDV\ForcaVendasController@list')->name('admin.pdv');
    Route::get('/events/{id}/forca-de-vendas', 'PDV\ForcaVendasController@create')->name('admin.events.pdv');
    Route::get('/forca-de-vendas/{id}/imprimir', 'PDV\ForcaVendasController@imprimir')->name('admin.pdv.imprimir');
    Route::post('/forca-de-vendas/fechar-venda', 'PDV\ForcaVendasController@store')->name('admin.pdv.store');
    Route::get('/carregar-modelo', 'PDV\ForcaVendasController@carregaModelo')->name('admin.carregaModelo');
    Route::get('/controle-financeiro', 'PDV\ForcaVendasController@index')->name('admin.pdv.sales');
    Route::post('/payment-method', 'PDV\ForcaVendasController@store')->name('admin.store');
    Route::post('/abrir-caixa', 'PDV\ForcaVendasController@abrirCaixa')->name('admin.abrirCaixa');
    Route::get('/sales/{id}', 'PDV\ForcaVendasController@printSale')->name('sales.printSale');
    Route::get('/sales/canceled/{id}', 'PDV\ForcaVendasController@canceled')->name('sales.canceled');


    /**
     * produtos
     */
    Route::get('/produtos', 'Produtos\ProdutosController@index')->name('produtos.index');
    Route::get('/produtos/{id}/editar', 'Produtos\ProdutosController@edit')->name('admin.produtos.edit');
    Route::get('/produtos/cadastrar', 'Produtos\ProdutosController@create')->name('admin.produto.create');
    Route::get('/produtos/lista-produtos', 'Produtos\ProdutosController@all')->name('admin.produtos.all');
    Route::post('/produtos/store', 'Produtos\ProdutosController@store')->name('admin.produto.store');
    Route::post('/produtos/{id}/update', 'Produtos\ProdutosController@update')->name('admin.produto.update');

    /**
     * notifications
     */
    Route::get('/notifications/show', 'Notification\NotificationsController@index')->name('notifications.index');

});

Route::get('/test', 'Notification\NotificationsController@create');

Broadcast::routes();

Route::get('/address', function(){
    $endereco = [];
    $google = new \App\Lib\GoogleMaps\GoogleMaps();
    $return = $google->getLatLongByAddress('rua leila diniz, 531 pinhais paraná');
    if(!empty($return)){
        $resultado = $return->results[0]->address_components;
        $endereco = [
          'number' => $resultado[0]->long_name,
          'street' => $resultado[1]->long_name,
          'municipio' => $resultado[2]->long_name,
          'cidade' => $resultado[3]->long_name,
          'estado' => $resultado[4]->long_name,
          'pais' => $resultado[5]->long_name,
          'cep' => $resultado[6]->long_name,
        ];
    }

app/User.php
<?php

namespace App;

use App\Model\Empresa;
use Carbon\Carbon;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    public function scopeFindRememberToken($query, string $token){
        return $query->where('remember_token', $token);
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $guarded = ['confirm_password'];

    public function place()
    {
        return $this->belongsTo(Place::class);
    }


    public function empresa()
    {
        return $this->belongsTo(Empresa::class, 'empresas_id');
    }

    public function promoter()
    {
        return $this->hasOne(Promoter::class, 'user_id', 'id');
    }

    public function role()
    {
        return $this->hasOne(Role::class, 'id', 'roles_id');
    }


    public function getCriadoEmAttribute()
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $this->attributes['created_at'])->format('d/m/Y');
    }

}

app/Http/Controllers/PDV/FechamentosController.php
<?php

namespace App\Http\Controllers\PDV;

use App\Model\Pagamento\CloseSale;
use App\Model\Pagamento\OpenSale;
use App\Services\Event\EventService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FechamentosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = validator(
            $request->all(),
            [
                'events_id' => 'required|integer',
                'users_id'  => 'required|integer',
            ]
        );

        if($validator->fails()){
            return response()->json($validator->errors()->all(), 422);
        }

        $closureSales = new CloseSale($request->all());
        $closureSales->secure_id = uniqid(date('YmdHis'));
        $closureSales->save();

        return response()->json($closureSales);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(int $id)
    {
        $closeSales = CloseSale::with(['event', 'user'])->find($id);
        $openSales  = OpenSale::where([
            'events_id' => $closeSales->events_id,
            'users_id'  => $closeSales->users_id
        ])->first();

        return view('pdv.fechamento.show')->with('fechamento', collect([
            'abertura'     => $openSales,
            'fechamento'   => $closeSales,
            'vendas_canceladas'   => EventService::vendasCanceladas($closeSales->events_id, $closeSales->users_id),
            'produtos'            => EventService::produtosMaisVendios($closeSales->events_id, $closeSales->users_id),
            'resumo_caixa'        => EventService::paymentSales($closeSales->events_id, $closeSales->users_id),
        ]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


}

resources/views/pdv/fechamento/show.blade.php
@extends('layouts.print')

@section('content')

    <style>
        body{
            font-size: 16px;
        }
        table{

            width: 100%;
        }
        thead>tr{
            padding: 5px;
        }
        thead>tr>td{
            border-bottom: 1.5px dashed black;
        }
        tfoot>tr>td{
            border-top: 1.5px dashed black;
        }
        tr>td{
            padding: 3px;
        }
    </style>
<div style="width: 600px; margin: auto;">
<pre>
<span style="margin-bottom: 0px; padding-bottom: 0px; font-size: 50px; font-weight: bold; text-align: center">
 Fechamento de Caixa
</span>

<span style="margin: 0 0; padding: 0px 0px; ">
Secure ID:
<strong style="font-size: 18px">{{$fechamento['fechamento']->secure_id}}</strong>
</span>

Evento: <strong>{{$fechamento['fechamento']->event->title}}</strong>
Abertura: <strong>{{($fechamento['abertura']!=null)?$fechamento['abertura']->criado_em:null}}</strong>
Fechamento: <strong>{{$fechamento['fechamento']->criado_em}}</strong>
Responsavel: <strong>{{$fechamento['fechamento']->user->name}}</strong>


    <span style="margin-bottom: 0px; padding-bottom: 0px; font-size: 30px; font-weight: bold; text-align: center">
          Resumo do Caixa
    </span>
@php $total =0;@endphp
@foreach($fechamento['resumo_caixa'] as $resumo)
@php $total += $resumo->valor;@endphp
{{$resumo->nome}}:
<strong style="font-size: 22px;">R$ {{number_format($resumo->valor, 2, ',', '.')}}</strong>
@endforeach
Total:
<strong style="font-size: 22px;">R$ {{number_format($total, 2, ',', '.')}}</strong>

    <span style="margin-bottom: 0px; padding-bottom: 0px; font-size: 30px; font-weight: bold; text-align: center">
          Tipo Transação
    </span>
    <table>
        <thead>
            <tr>
                <td>Tipo</td>
                <td style="text-align: right">R$</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Venda de Ticket</td>
                <td style="text-align: right">{{number_format($fechamento['produtos']->sum('value'), 2, ',', '.')}}</td>
            </tr>
            <tr>
                <td>Cancelamentos</td>
                <td style="text-align: right">{{number_format($fechamento['vendas_canceladas']->sum('total_value'), 2, ',', '.')}}</td>
            </tr>
        </tbody>
    </table>
    <span style="margin-bottom: 0px; padding-bottom: 0px; font-size: 30px; font-weight: bold; text-align: center">
          Vendas Produtos
    </span>
    <table>
        <thead>
            <tr>
                <td>Produto</td>
                <td>Qtde</td>
                <td style="text-align: right">R$</td>
            </tr>
        </thead>
        <tbody>
            @php $total =0;@endphp
            @foreach($fechamento['produtos'] as $sales)
                @php $total += $sales->value;@endphp
                <tr>
                    <td>{{$sales->produto->name}}</td>
                    <td>{{$sales->amount}}</td>
                    <td style="text-align: right">{{number_format($sales->value, 2, ',', '.')}}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" style="text-align: right;"><strong>Total R$ {{number_format($total, 2, ',', '.')}}</strong></td>
            </tr>
        </tfoot>
    </table>



Assinatura:




----------------------------------------------------------------------
                      <strong>{{$fechamento['fechamento']->user->name}}</strong>
                        {{$fechamento['fechamento']->criado_em}}


                      <img src="{{asset('dashboard/images/logo-payticket-b.png')}}" alt="{{ env('APP_NAME') }}" height="50" >
                        www.payticket.com.br
</pre>
</div>
@endsection